// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin "github.com/aliaxy/zero-link/services/link-api/internal/handler/admin"
	health "github.com/aliaxy/zero-link/services/link-api/internal/handler/health"
	redirect "github.com/aliaxy/zero-link/services/link-api/internal/handler/redirect"
	"github.com/aliaxy/zero-link/services/link-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: admin.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/links",
					Handler: admin.CreateShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/links",
					Handler: admin.ListShortLinksHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/links/:id",
					Handler: admin.GetShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/admin/links/:id",
					Handler: admin.UpdateShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/links/:id",
					Handler: admin.DeleteShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/links/:id/stats",
					Handler: admin.GetLinkStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/profile",
					Handler: admin.ProfileHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: health.ReadyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AnalyticsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:code",
					Handler: redirect.RedirectHandler(serverCtx),
				},
			}...,
		),
	)
}
