// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/aliaxy/zero-link/services/link-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: ReadyHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AnalyticsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:code",
					Handler: RedirectHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/admin/links",
					Handler: CreateShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/links",
					Handler: ListShortLinksHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/links/:id",
					Handler: GetShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/admin/links/:id",
					Handler: UpdateShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/admin/links/:id",
					Handler: DeleteShortLinkHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/links/:id/stats",
					Handler: GetLinkStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/profile",
					Handler: ProfileHandler(serverCtx),
				},
			}...,
		),
	)
}
