// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package server

import (
	"context"

	analyticsservicelogic "github.com/aliaxy/zero-link/services/link-rpc/internal/logic/analyticsservice"
	"github.com/aliaxy/zero-link/services/link-rpc/internal/svc"
	linkv1 "github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"
)

type AnalyticsServiceServer struct {
	svcCtx *svc.ServiceContext
	linkv1.UnimplementedAnalyticsServiceServer
}

func NewAnalyticsServiceServer(svcCtx *svc.ServiceContext) *AnalyticsServiceServer {
	return &AnalyticsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AnalyticsServiceServer) RecordVisit(ctx context.Context, in *linkv1.RecordVisitRequest) (*linkv1.RecordVisitResponse, error) {
	l := analyticsservicelogic.NewRecordVisitLogic(ctx, s.svcCtx)
	return l.RecordVisit(in)
}

func (s *AnalyticsServiceServer) GetLinkStats(ctx context.Context, in *linkv1.GetLinkStatsRequest) (*linkv1.GetLinkStatsResponse, error) {
	l := analyticsservicelogic.NewGetLinkStatsLogic(ctx, s.svcCtx)
	return l.GetLinkStats(in)
}
