### login - admin login
# @name login
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

### profile - get admin profile
# @name profile
GET {{baseUrl}}/admin/profile
Authorization: Bearer {{token}}

### list-links - get all links
# @name listLinks
GET {{baseUrl}}/admin/links
Authorization: Bearer {{token}}

### create-link - create a new link
# @name createLink
POST {{baseUrl}}/admin/links
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "origin_url": "https://example.com"
}

### get-link - get a link by id
# @name getLink
GET {{baseUrl}}/admin/links/{{linkId}}
Authorization: Bearer {{token}}

### update-link - update a link by id
# @name updateLink
PATCH {{baseUrl}}/admin/links/{{linkId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "origin_url": "https://www.baidu.com",
  "title": "Baidu"
}

### delete-link - delete a link by id
# @name deleteLink
DELETE {{baseUrl}}/admin/links/{{linkId}}
Authorization: Bearer {{token}}
