// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package linkservice

import (
	"context"

	"github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminProfile              = linkv1.AdminProfile
	AuthenticateAdminRequest  = linkv1.AuthenticateAdminRequest
	AuthenticateAdminResponse = linkv1.AuthenticateAdminResponse
	ChangePasswordRequest     = linkv1.ChangePasswordRequest
	ChangePasswordResponse    = linkv1.ChangePasswordResponse
	CheckRequest              = linkv1.CheckRequest
	CheckResponse             = linkv1.CheckResponse
	CreateShortLinkRequest    = linkv1.CreateShortLinkRequest
	CreateShortLinkResponse   = linkv1.CreateShortLinkResponse
	DailyStat                 = linkv1.DailyStat
	DeleteShortLinkRequest    = linkv1.DeleteShortLinkRequest
	DeleteShortLinkResponse   = linkv1.DeleteShortLinkResponse
	GetAdminProfileRequest    = linkv1.GetAdminProfileRequest
	GetAdminProfileResponse   = linkv1.GetAdminProfileResponse
	GetLinkStatsRequest       = linkv1.GetLinkStatsRequest
	GetLinkStatsResponse      = linkv1.GetLinkStatsResponse
	GetShortLinkRequest       = linkv1.GetShortLinkRequest
	GetShortLinkResponse      = linkv1.GetShortLinkResponse
	ListShortLinksRequest     = linkv1.ListShortLinksRequest
	ListShortLinksResponse    = linkv1.ListShortLinksResponse
	RecordVisitRequest        = linkv1.RecordVisitRequest
	RecordVisitResponse       = linkv1.RecordVisitResponse
	ResolveShortLinkRequest   = linkv1.ResolveShortLinkRequest
	ResolveShortLinkResponse  = linkv1.ResolveShortLinkResponse
	ShortLink                 = linkv1.ShortLink
	ShortLinkSummary          = linkv1.ShortLinkSummary
	UpdateShortLinkRequest    = linkv1.UpdateShortLinkRequest
	UpdateShortLinkResponse   = linkv1.UpdateShortLinkResponse

	LinkService interface {
		CreateShortLink(ctx context.Context, in *CreateShortLinkRequest, opts ...grpc.CallOption) (*CreateShortLinkResponse, error)
		ListShortLinks(ctx context.Context, in *ListShortLinksRequest, opts ...grpc.CallOption) (*ListShortLinksResponse, error)
		GetShortLink(ctx context.Context, in *GetShortLinkRequest, opts ...grpc.CallOption) (*GetShortLinkResponse, error)
		UpdateShortLink(ctx context.Context, in *UpdateShortLinkRequest, opts ...grpc.CallOption) (*UpdateShortLinkResponse, error)
		DeleteShortLink(ctx context.Context, in *DeleteShortLinkRequest, opts ...grpc.CallOption) (*DeleteShortLinkResponse, error)
		ResolveShortLink(ctx context.Context, in *ResolveShortLinkRequest, opts ...grpc.CallOption) (*ResolveShortLinkResponse, error)
	}

	defaultLinkService struct {
		cli zrpc.Client
	}
)

func NewLinkService(cli zrpc.Client) LinkService {
	return &defaultLinkService{
		cli: cli,
	}
}

func (m *defaultLinkService) CreateShortLink(ctx context.Context, in *CreateShortLinkRequest, opts ...grpc.CallOption) (*CreateShortLinkResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.CreateShortLink(ctx, in, opts...)
}

func (m *defaultLinkService) ListShortLinks(ctx context.Context, in *ListShortLinksRequest, opts ...grpc.CallOption) (*ListShortLinksResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.ListShortLinks(ctx, in, opts...)
}

func (m *defaultLinkService) GetShortLink(ctx context.Context, in *GetShortLinkRequest, opts ...grpc.CallOption) (*GetShortLinkResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.GetShortLink(ctx, in, opts...)
}

func (m *defaultLinkService) UpdateShortLink(ctx context.Context, in *UpdateShortLinkRequest, opts ...grpc.CallOption) (*UpdateShortLinkResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.UpdateShortLink(ctx, in, opts...)
}

func (m *defaultLinkService) DeleteShortLink(ctx context.Context, in *DeleteShortLinkRequest, opts ...grpc.CallOption) (*DeleteShortLinkResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.DeleteShortLink(ctx, in, opts...)
}

func (m *defaultLinkService) ResolveShortLink(ctx context.Context, in *ResolveShortLinkRequest, opts ...grpc.CallOption) (*ResolveShortLinkResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.ResolveShortLink(ctx, in, opts...)
}
