// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package analyticsservice

import (
	"context"

	"github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminProfile              = linkv1.AdminProfile
	AuthenticateAdminRequest  = linkv1.AuthenticateAdminRequest
	AuthenticateAdminResponse = linkv1.AuthenticateAdminResponse
	CheckRequest              = linkv1.CheckRequest
	CheckResponse             = linkv1.CheckResponse
	CreateShortLinkRequest    = linkv1.CreateShortLinkRequest
	CreateShortLinkResponse   = linkv1.CreateShortLinkResponse
	DailyStat                 = linkv1.DailyStat
	DeleteShortLinkRequest    = linkv1.DeleteShortLinkRequest
	DeleteShortLinkResponse   = linkv1.DeleteShortLinkResponse
	GetAdminProfileRequest    = linkv1.GetAdminProfileRequest
	GetAdminProfileResponse   = linkv1.GetAdminProfileResponse
	GetLinkStatsRequest       = linkv1.GetLinkStatsRequest
	GetLinkStatsResponse      = linkv1.GetLinkStatsResponse
	GetShortLinkRequest       = linkv1.GetShortLinkRequest
	GetShortLinkResponse      = linkv1.GetShortLinkResponse
	ListShortLinksRequest     = linkv1.ListShortLinksRequest
	ListShortLinksResponse    = linkv1.ListShortLinksResponse
	RecordVisitRequest        = linkv1.RecordVisitRequest
	RecordVisitResponse       = linkv1.RecordVisitResponse
	ResolveShortLinkRequest   = linkv1.ResolveShortLinkRequest
	ResolveShortLinkResponse  = linkv1.ResolveShortLinkResponse
	ShortLink                 = linkv1.ShortLink
	ShortLinkSummary          = linkv1.ShortLinkSummary
	UpdateShortLinkRequest    = linkv1.UpdateShortLinkRequest
	UpdateShortLinkResponse   = linkv1.UpdateShortLinkResponse

	AnalyticsService interface {
		RecordVisit(ctx context.Context, in *RecordVisitRequest, opts ...grpc.CallOption) (*RecordVisitResponse, error)
		GetLinkStats(ctx context.Context, in *GetLinkStatsRequest, opts ...grpc.CallOption) (*GetLinkStatsResponse, error)
	}

	defaultAnalyticsService struct {
		cli zrpc.Client
	}
)

func NewAnalyticsService(cli zrpc.Client) AnalyticsService {
	return &defaultAnalyticsService{
		cli: cli,
	}
}

func (m *defaultAnalyticsService) RecordVisit(ctx context.Context, in *RecordVisitRequest, opts ...grpc.CallOption) (*RecordVisitResponse, error) {
	client := linkv1.NewAnalyticsServiceClient(m.cli.Conn())
	return client.RecordVisit(ctx, in, opts...)
}

func (m *defaultAnalyticsService) GetLinkStats(ctx context.Context, in *GetLinkStatsRequest, opts ...grpc.CallOption) (*GetLinkStatsResponse, error) {
	client := linkv1.NewAnalyticsServiceClient(m.cli.Conn())
	return client.GetLinkStats(ctx, in, opts...)
}
