// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package server

import (
	"context"

	"github.com/aliaxy/zero-link/services/link-rpc/internal/logic/adminservice"
	"github.com/aliaxy/zero-link/services/link-rpc/internal/svc"
	"github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	linkv1.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServiceServer) AuthenticateAdmin(ctx context.Context, in *linkv1.AuthenticateAdminRequest) (*linkv1.AuthenticateAdminResponse, error) {
	l := adminservicelogic.NewAuthenticateAdminLogic(ctx, s.svcCtx)
	return l.AuthenticateAdmin(in)
}

func (s *AdminServiceServer) GetAdminProfile(ctx context.Context, in *linkv1.GetAdminProfileRequest) (*linkv1.GetAdminProfileResponse, error) {
	l := adminservicelogic.NewGetAdminProfileLogic(ctx, s.svcCtx)
	return l.GetAdminProfile(in)
}

func (s *AdminServiceServer) ChangePassword(ctx context.Context, in *linkv1.ChangePasswordRequest) (*linkv1.ChangePasswordResponse, error) {
	l := adminservicelogic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}
