// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package server

import (
	"context"

	healthservicelogic "github.com/aliaxy/zero-link/services/link-rpc/internal/logic/healthservice"
	"github.com/aliaxy/zero-link/services/link-rpc/internal/svc"
	linkv1 "github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"
)

type HealthServiceServer struct {
	svcCtx *svc.ServiceContext
	linkv1.UnimplementedHealthServiceServer
}

func NewHealthServiceServer(svcCtx *svc.ServiceContext) *HealthServiceServer {
	return &HealthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *HealthServiceServer) Check(ctx context.Context, in *linkv1.CheckRequest) (*linkv1.CheckResponse, error) {
	l := healthservicelogic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
