// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package server

import (
	"context"

	linkservicelogic "github.com/aliaxy/zero-link/services/link-rpc/internal/logic/linkservice"
	"github.com/aliaxy/zero-link/services/link-rpc/internal/svc"
	linkv1 "github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"
)

type LinkServiceServer struct {
	svcCtx *svc.ServiceContext
	linkv1.UnimplementedLinkServiceServer
}

func NewLinkServiceServer(svcCtx *svc.ServiceContext) *LinkServiceServer {
	return &LinkServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LinkServiceServer) CreateShortLink(ctx context.Context, in *linkv1.CreateShortLinkRequest) (*linkv1.CreateShortLinkResponse, error) {
	l := linkservicelogic.NewCreateShortLinkLogic(ctx, s.svcCtx)
	return l.CreateShortLink(in)
}

func (s *LinkServiceServer) ListShortLinks(ctx context.Context, in *linkv1.ListShortLinksRequest) (*linkv1.ListShortLinksResponse, error) {
	l := linkservicelogic.NewListShortLinksLogic(ctx, s.svcCtx)
	return l.ListShortLinks(in)
}

func (s *LinkServiceServer) GetShortLink(ctx context.Context, in *linkv1.GetShortLinkRequest) (*linkv1.GetShortLinkResponse, error) {
	l := linkservicelogic.NewGetShortLinkLogic(ctx, s.svcCtx)
	return l.GetShortLink(in)
}

func (s *LinkServiceServer) UpdateShortLink(ctx context.Context, in *linkv1.UpdateShortLinkRequest) (*linkv1.UpdateShortLinkResponse, error) {
	l := linkservicelogic.NewUpdateShortLinkLogic(ctx, s.svcCtx)
	return l.UpdateShortLink(in)
}

func (s *LinkServiceServer) DeleteShortLink(ctx context.Context, in *linkv1.DeleteShortLinkRequest) (*linkv1.DeleteShortLinkResponse, error) {
	l := linkservicelogic.NewDeleteShortLinkLogic(ctx, s.svcCtx)
	return l.DeleteShortLink(in)
}

func (s *LinkServiceServer) ResolveShortLink(ctx context.Context, in *linkv1.ResolveShortLinkRequest) (*linkv1.ResolveShortLinkResponse, error) {
	l := linkservicelogic.NewResolveShortLinkLogic(ctx, s.svcCtx)
	return l.ResolveShortLink(in)
}
