// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUserFieldNames          = builder.RawFieldNames(&AdminUser{})
	adminUserRows                = strings.Join(adminUserFieldNames, ",")
	adminUserRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUserRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAdminUserIdPrefix       = "cache:adminUser:id:"
	cacheAdminUserUsernamePrefix = "cache:adminUser:username:"
)

type (
	adminUserModel interface {
		Insert(ctx context.Context, data *AdminUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminUser, error)
		FindOneByUsername(ctx context.Context, username string) (*AdminUser, error)
		Update(ctx context.Context, data *AdminUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminUserModel struct {
		sqlc.CachedConn
		table string
	}

	AdminUser struct {
		Id           int64     `db:"id"`
		Username     string    `db:"username"`
		PasswordHash string    `db:"password_hash"`
		Status       int64     `db:"status"`
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newAdminUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminUserModel {
	return &defaultAdminUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`admin_user`",
	}
}

func (m *defaultAdminUserModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, id)
	adminUserUsernameKey := fmt.Sprintf("%s%v", cacheAdminUserUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, adminUserIdKey, adminUserUsernameKey)
	return err
}

func (m *defaultAdminUserModel) FindOne(ctx context.Context, id int64) (*AdminUser, error) {
	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, id)
	var resp AdminUser
	err := m.QueryRowCtx(ctx, &resp, adminUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserModel) FindOneByUsername(ctx context.Context, username string) (*AdminUser, error) {
	adminUserUsernameKey := fmt.Sprintf("%s%v", cacheAdminUserUsernamePrefix, username)
	var resp AdminUser
	err := m.QueryRowIndexCtx(ctx, &resp, adminUserUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminUserRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, username); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserModel) Insert(ctx context.Context, data *AdminUser) (sql.Result, error) {
	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, data.Id)
	adminUserUsernameKey := fmt.Sprintf("%s%v", cacheAdminUserUsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, adminUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Username, data.PasswordHash, data.Status)
	}, adminUserIdKey, adminUserUsernameKey)
	return ret, err
}

func (m *defaultAdminUserModel) Update(ctx context.Context, newData *AdminUser) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, data.Id)
	adminUserUsernameKey := fmt.Sprintf("%s%v", cacheAdminUserUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Username, newData.PasswordHash, newData.Status, newData.Id)
	}, adminUserIdKey, adminUserUsernameKey)
	return err
}

func (m *defaultAdminUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, primary)
}

func (m *defaultAdminUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminUserModel) tableName() string {
	return m.table
}
