// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUserFieldNames          = builder.RawFieldNames(&AdminUser{})
	adminUserRows                = strings.Join(adminUserFieldNames, ",")
	adminUserRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUserRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminUserModel interface {
		Insert(ctx context.Context, data *AdminUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminUser, error)
		FindOneByUsername(ctx context.Context, username string) (*AdminUser, error)
		Update(ctx context.Context, data *AdminUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminUser struct {
		Id           int64     `db:"id"`
		Username     string    `db:"username"`
		PasswordHash string    `db:"password_hash"`
		Status       int64     `db:"status"`
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newAdminUserModel(conn sqlx.SqlConn) *defaultAdminUserModel {
	return &defaultAdminUserModel{
		conn:  conn,
		table: "`admin_user`",
	}
}

func (m *defaultAdminUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminUserModel) FindOne(ctx context.Context, id int64) (*AdminUser, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUserRows, m.table)
	var resp AdminUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserModel) FindOneByUsername(ctx context.Context, username string) (*AdminUser, error) {
	var resp AdminUser
	query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", adminUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserModel) Insert(ctx context.Context, data *AdminUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, adminUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.PasswordHash, data.Status)
	return ret, err
}

func (m *defaultAdminUserModel) Update(ctx context.Context, newData *AdminUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Username, newData.PasswordHash, newData.Status, newData.Id)
	return err
}

func (m *defaultAdminUserModel) tableName() string {
	return m.table
}
