// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	linkDailyStatFieldNames          = builder.RawFieldNames(&LinkDailyStat{})
	linkDailyStatRows                = strings.Join(linkDailyStatFieldNames, ",")
	linkDailyStatRowsExpectAutoSet   = strings.Join(stringx.Remove(linkDailyStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	linkDailyStatRowsWithPlaceHolder = strings.Join(stringx.Remove(linkDailyStatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	linkDailyStatModel interface {
		Insert(ctx context.Context, data *LinkDailyStat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LinkDailyStat, error)
		FindOneByLinkIdStatDate(ctx context.Context, linkId int64, statDate time.Time) (*LinkDailyStat, error)
		Update(ctx context.Context, data *LinkDailyStat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLinkDailyStatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LinkDailyStat struct {
		Id       int64     `db:"id"`
		LinkId   int64     `db:"link_id"`
		StatDate time.Time `db:"stat_date"`
		Pv       int64     `db:"pv"`
		Uv       int64     `db:"uv"`
	}
)

func newLinkDailyStatModel(conn sqlx.SqlConn) *defaultLinkDailyStatModel {
	return &defaultLinkDailyStatModel{
		conn:  conn,
		table: "`link_daily_stat`",
	}
}

func (m *defaultLinkDailyStatModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLinkDailyStatModel) FindOne(ctx context.Context, id int64) (*LinkDailyStat, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", linkDailyStatRows, m.table)
	var resp LinkDailyStat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLinkDailyStatModel) FindOneByLinkIdStatDate(ctx context.Context, linkId int64, statDate time.Time) (*LinkDailyStat, error) {
	var resp LinkDailyStat
	query := fmt.Sprintf("select %s from %s where `link_id` = ? and `stat_date` = ? limit 1", linkDailyStatRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, linkId, statDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLinkDailyStatModel) Insert(ctx context.Context, data *LinkDailyStat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, linkDailyStatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LinkId, data.StatDate, data.Pv, data.Uv)
	return ret, err
}

func (m *defaultLinkDailyStatModel) Update(ctx context.Context, newData *LinkDailyStat) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, linkDailyStatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.LinkId, newData.StatDate, newData.Pv, newData.Uv, newData.Id)
	return err
}

func (m *defaultLinkDailyStatModel) tableName() string {
	return m.table
}
