// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reservedCodeFieldNames          = builder.RawFieldNames(&ReservedCode{})
	reservedCodeRows                = strings.Join(reservedCodeFieldNames, ",")
	reservedCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(reservedCodeFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	reservedCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(reservedCodeFieldNames, "`code`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	reservedCodeModel interface {
		Insert(ctx context.Context, data *ReservedCode) (sql.Result, error)
		FindOne(ctx context.Context, code string) (*ReservedCode, error)
		Update(ctx context.Context, data *ReservedCode) error
		Delete(ctx context.Context, code string) error
	}

	defaultReservedCodeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ReservedCode struct {
		Code       string    `db:"code"`
		ReservedAt time.Time `db:"reserved_at"`
	}
)

func newReservedCodeModel(conn sqlx.SqlConn) *defaultReservedCodeModel {
	return &defaultReservedCodeModel{
		conn:  conn,
		table: "`reserved_code`",
	}
}

func (m *defaultReservedCodeModel) Delete(ctx context.Context, code string) error {
	query := fmt.Sprintf("delete from %s where `code` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, code)
	return err
}

func (m *defaultReservedCodeModel) FindOne(ctx context.Context, code string) (*ReservedCode, error) {
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", reservedCodeRows, m.table)
	var resp ReservedCode
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReservedCodeModel) Insert(ctx context.Context, data *ReservedCode) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, reservedCodeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.ReservedAt)
	return ret, err
}

func (m *defaultReservedCodeModel) Update(ctx context.Context, data *ReservedCode) error {
	query := fmt.Sprintf("update %s set %s where `code` = ?", m.table, reservedCodeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ReservedAt, data.Code)
	return err
}

func (m *defaultReservedCodeModel) tableName() string {
	return m.table
}
