// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shortLinkFieldNames          = builder.RawFieldNames(&ShortLink{})
	shortLinkRows                = strings.Join(shortLinkFieldNames, ",")
	shortLinkRowsExpectAutoSet   = strings.Join(stringx.Remove(shortLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shortLinkRowsWithPlaceHolder = strings.Join(stringx.Remove(shortLinkFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shortLinkModel interface {
		Insert(ctx context.Context, data *ShortLink) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ShortLink, error)
		FindOneByCode(ctx context.Context, code string) (*ShortLink, error)
		Update(ctx context.Context, data *ShortLink) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShortLinkModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShortLink struct {
		Id          int64        `db:"id"`
		Code        string       `db:"code"`
		OriginUrl   string       `db:"origin_url"`
		Title       string       `db:"title"`
		Description string       `db:"description"`
		Status      int64        `db:"status"`
		ExpireAt    sql.NullTime `db:"expire_at"`
		CreatedBy   int64        `db:"created_by"`
		CreatedAt   time.Time    `db:"created_at"`
		UpdatedAt   time.Time    `db:"updated_at"`
		DeletedAt   sql.NullTime `db:"deleted_at"`
	}
)

func newShortLinkModel(conn sqlx.SqlConn) *defaultShortLinkModel {
	return &defaultShortLinkModel{
		conn:  conn,
		table: "`short_link`",
	}
}

func (m *defaultShortLinkModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShortLinkModel) FindOne(ctx context.Context, id int64) (*ShortLink, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortLinkRows, m.table)
	var resp ShortLink
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortLinkModel) FindOneByCode(ctx context.Context, code string) (*ShortLink, error) {
	var resp ShortLink
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", shortLinkRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortLinkModel) Insert(ctx context.Context, data *ShortLink) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, shortLinkRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.OriginUrl, data.Title, data.Description, data.Status, data.ExpireAt, data.CreatedBy, data.DeletedAt)
	return ret, err
}

func (m *defaultShortLinkModel) Update(ctx context.Context, newData *ShortLink) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shortLinkRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.OriginUrl, newData.Title, newData.Description, newData.Status, newData.ExpireAt, newData.CreatedBy, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultShortLinkModel) tableName() string {
	return m.table
}
