// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	visitEventFieldNames          = builder.RawFieldNames(&VisitEvent{})
	visitEventRows                = strings.Join(visitEventFieldNames, ",")
	visitEventRowsExpectAutoSet   = strings.Join(stringx.Remove(visitEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	visitEventRowsWithPlaceHolder = strings.Join(stringx.Remove(visitEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	visitEventModel interface {
		Insert(ctx context.Context, data *VisitEvent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VisitEvent, error)
		Update(ctx context.Context, data *VisitEvent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVisitEventModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VisitEvent struct {
		Id        int64     `db:"id"`
		LinkId    int64     `db:"link_id"`
		Code      string    `db:"code"`
		VisitedAt time.Time `db:"visited_at"`
		IpHash    string    `db:"ip_hash"`
		UserAgent string    `db:"user_agent"`
		Referer   string    `db:"referer"`
		Device    string    `db:"device"`
	}
)

func newVisitEventModel(conn sqlx.SqlConn) *defaultVisitEventModel {
	return &defaultVisitEventModel{
		conn:  conn,
		table: "`visit_event`",
	}
}

func (m *defaultVisitEventModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVisitEventModel) FindOne(ctx context.Context, id int64) (*VisitEvent, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", visitEventRows, m.table)
	var resp VisitEvent
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVisitEventModel) Insert(ctx context.Context, data *VisitEvent) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, visitEventRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LinkId, data.Code, data.VisitedAt, data.IpHash, data.UserAgent, data.Referer, data.Device)
	return ret, err
}

func (m *defaultVisitEventModel) Update(ctx context.Context, data *VisitEvent) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, visitEventRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LinkId, data.Code, data.VisitedAt, data.IpHash, data.UserAgent, data.Referer, data.Device, data.Id)
	return err
}

func (m *defaultVisitEventModel) tableName() string {
	return m.table
}
