// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package server

import (
	"context"

	"github.com/aliaxy/zero-link/services/link-rpc/internal/logic"
	"github.com/aliaxy/zero-link/services/link-rpc/internal/svc"
	linkv1 "github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"
)

type LinkServer struct {
	svcCtx *svc.ServiceContext
	linkv1.UnimplementedLinkServiceServer
}

func NewLinkServer(svcCtx *svc.ServiceContext) *LinkServer {
	return &LinkServer{
		svcCtx: svcCtx,
	}
}

func (s *LinkServer) Check(ctx context.Context, in *linkv1.CheckRequest) (*linkv1.CheckResponse, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
