// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package server

import (
	"context"

	"github.com/aliaxy/zero-link/services/link-rpc/internal/logic"
	"github.com/aliaxy/zero-link/services/link-rpc/internal/svc"
	"github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"
)

type LinkServiceServer struct {
	svcCtx *svc.ServiceContext
	linkv1.UnimplementedLinkServiceServer
}

func NewLinkServiceServer(svcCtx *svc.ServiceContext) *LinkServiceServer {
	return &LinkServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LinkServiceServer) Check(ctx context.Context, in *linkv1.CheckRequest) (*linkv1.CheckResponse, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}
