// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type HealthResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type ReadyResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}
