// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: link.proto

package linkservice

import (
	"context"

	"github.com/aliaxy/zero-link/services/link-rpc/pb/link/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckRequest  = linkv1.CheckRequest
	CheckResponse = linkv1.CheckResponse

	LinkService interface {
		Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	}

	defaultLinkService struct {
		cli zrpc.Client
	}
)

func NewLinkService(cli zrpc.Client) LinkService {
	return &defaultLinkService{
		cli: cli,
	}
}

func (m *defaultLinkService) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	client := linkv1.NewLinkServiceClient(m.cli.Conn())
	return client.Check(ctx, in, opts...)
}
